#include "loss_observatory/model/method.hpp"

#include <array>

namespace loss_observatory {
namespace {

constexpr MethodSemantics kSemantics[] = {
    {MeasurementMethod::Unknown, "unknown", Granularity::Unknown, false, true, false, false, false, false,
     "No method declared. Evidence using this method is rejected rather than guessed at."},
    {MeasurementMethod::CounterDelta, "counter-delta", Granularity::Queue, false, false, true, false, false,
     true,
     "Difference between two readings of the same counter. Resolves to the counter binding: a queue counter "
     "supports a queue-scoped claim, a port counter supports a port-scoped one."},
    {MeasurementMethod::ProbeRoundTrip, "probe-round-trip", Granularity::Path, false, true, false, true, false,
     true,
     "Active round-trip probe. Bounds the path as a whole; it cannot name an interior hop without per-hop "
     "scoping, which this runtime does not assume."},
    {MeasurementMethod::ProbeOneWay, "probe-one-way", Granularity::Link, true, true, false, true, false, false,
     "One-way probe. Requires a synchronised clock domain to interpret; unsupported until a deployment "
     "declares one."},
    {MeasurementMethod::SequenceGap, "sequence-gap", Granularity::Flow, false, true, false, true, false, true,
     "Gap analysis over a delivered sequence space. Flow-scoped by construction: a gap at the receiver does "
     "not say which hop dropped the packet."},
    {MeasurementMethod::EndpointComparison, "endpoint-comparison", Granularity::Flow, false, true, false, true,
     false, true,
     "Sender and receiver counts compared for the same flow, generation, and window. Flow-scoped."},
    {MeasurementMethod::SyntheticInjection, "synthetic-injection", Granularity::Queue, false, false, false,
     false, true, true,
     "Generated by this repository deterministic fixtures. Always labelled synthetic and never presented as "
     "a hardware measurement."},
};

constexpr std::size_t kSemanticsCount = sizeof(kSemantics) / sizeof(kSemantics[0]);

}  // namespace

std::string_view to_string(MeasurementMethod method) noexcept {
  switch (method) {
    case MeasurementMethod::Unknown:
      return "unknown";
    case MeasurementMethod::CounterDelta:
      return "counter-delta";
    case MeasurementMethod::ProbeRoundTrip:
      return "probe-round-trip";
    case MeasurementMethod::ProbeOneWay:
      return "probe-one-way";
    case MeasurementMethod::SequenceGap:
      return "sequence-gap";
    case MeasurementMethod::EndpointComparison:
      return "endpoint-comparison";
    case MeasurementMethod::SyntheticInjection:
      return "synthetic-injection";
  }
  return "unknown";
}

Result<MeasurementMethod> parse_measurement_method(std::string_view text) {
  if (text == "unknown") {
    return MeasurementMethod::Unknown;
  }
  if (text == "counter-delta" || text == "counter") {
    return MeasurementMethod::CounterDelta;
  }
  if (text == "probe-round-trip" || text == "probe-rtt") {
    return MeasurementMethod::ProbeRoundTrip;
  }
  if (text == "probe-one-way" || text == "probe-owd") {
    return MeasurementMethod::ProbeOneWay;
  }
  if (text == "sequence-gap" || text == "sequence") {
    return MeasurementMethod::SequenceGap;
  }
  if (text == "endpoint-comparison" || text == "endpoint") {
    return MeasurementMethod::EndpointComparison;
  }
  if (text == "synthetic-injection" || text == "synthetic") {
    return MeasurementMethod::SyntheticInjection;
  }
  return make_status(StatusCode::InvalidArgument, "unknown measurement method");
}

const MethodSemantics& semantics_of(MeasurementMethod method) noexcept {
  const auto index = static_cast<std::size_t>(method);
  if (index >= kSemanticsCount) {
    return kSemantics[0];
  }
  return kSemantics[index];
}

bool method_is_usable(MeasurementMethod method, bool clock_synchronized) noexcept {
  const MethodSemantics& semantics = semantics_of(method);
  if (!semantics.implemented) {
    return false;
  }
  if (semantics.requires_synchronized_clocks && !clock_synchronized) {
    return false;
  }
  return true;
}

std::string_view method_unusable_reason(MeasurementMethod method, bool clock_synchronized) noexcept {
  const MethodSemantics& semantics = semantics_of(method);
  if (!semantics.implemented) {
    return "method is declared but not implemented by this runtime";
  }
  if (semantics.requires_synchronized_clocks && !clock_synchronized) {
    return "method requires a synchronised clock domain, which this deployment has not declared";
  }
  return {};
}

std::vector<MeasurementMethod> all_measurement_methods() {
  return {MeasurementMethod::Unknown,        MeasurementMethod::CounterDelta,
          MeasurementMethod::ProbeRoundTrip, MeasurementMethod::ProbeOneWay,
          MeasurementMethod::SequenceGap,    MeasurementMethod::EndpointComparison,
          MeasurementMethod::SyntheticInjection};
}

}  // namespace loss_observatory
