#pragma once

#include <cstdint>
#include <map>
#include <string>
#include <string_view>
#include <vector>

#include "loss_observatory/engine.hpp"

namespace loss_observatory {

/// Deterministic line-oriented command language.
///
/// Used by the locctl tool, by the end-to-end process tests, and by the export
/// format, so a scenario written by hand, generated by a test, or exported from
/// a live engine all flow through exactly one parser.
///
/// Grammar (one command per line; '#' starts a comment):
///
///   source id=<ident> name=<text> kind=<kind> authority=<authority>
///   incarnation source=<ident> epoch=<ident> name=<text> at=<time>
///   link id=<ident> a=<n:p> b=<n:p> kind=<kind>
///   path id=<ident> kind=<kind> rev=<ident> hops=<n:p>-><n:p>,<n:p>-><n:p>
///   queue id=<ident> node=<ident> port=<ident> priority=<ident> kind=<kind>
///   flow id=<ident> src=<n:p> dst=<n:p> proto=<ident> path=<ident> gen=<ident>
///   counter source= epoch= gen=<ident> counter=<ident> scope=<scope>
///           value=<u64> bits=<n> class=<granularity> [node= port= queue= link=]
///           [seq=] [observed=<time>] [received=<time>]
///   probe   source= epoch= gen= probe=<ident> sent= received= [timeout=]
///           [ttl=] [oneway=true] class=<granularity> flow= ...
///   sequence source= epoch= gen= flow= low= high= received= [restart=true] ...
///   endpoint source= epoch= gen= flow= role=sender|receiver node= port= count= ...
///   op classify|localize|history|explain|export flow=<ident> [at=<time>] [gran=]
///
/// Unknown verbs and unknown keys are diagnostics, never silent defaults. A key
/// that a verb does not understand is an error, so a typo cannot quietly change
/// what a scenario means.

enum class ScriptCommandKind : std::uint8_t {
  Source = 0,
  Incarnation,
  Link,
  Path,
  Queue,
  Flow,
  Counter,
  Probe,
  Sequence,
  Endpoint,
  Operation,
  Setting,
  Comment,
};

[[nodiscard]] std::string_view to_string(ScriptCommandKind kind) noexcept;

struct ScriptDiagnostic {
  std::size_t line{0};
  std::string severity{"error"};
  std::string message{};

  [[nodiscard]] std::string to_string() const;
};

struct ScriptCommand {
  ScriptCommandKind kind{ScriptCommandKind::Comment};
  std::size_t line{0};
  std::string verb{};
  std::map<std::string, std::string> fields{};
  std::string raw{};

  [[nodiscard]] bool has(std::string_view key) const;
  [[nodiscard]] std::string get(std::string_view key, std::string_view fallback = {}) const;
};

struct ScriptProgram {
  std::vector<ScriptCommand> commands{};
  std::vector<ScriptDiagnostic> diagnostics{};
  std::size_t lines_parsed{0};
  bool truncated{false};

  [[nodiscard]] bool ok() const;
  [[nodiscard]] std::size_t error_count() const;
};

struct ScriptLimits {
  std::size_t max_lines{1000000};
  /// Generous enough for a fully specified path (a hop is roughly eleven
  /// bytes) while still bounding the work a single line can demand.
  std::size_t max_line_bytes{8192};
  std::size_t max_fields_per_command{64};
  std::size_t max_commands{200000};
  std::size_t max_input_bytes{64ULL * 1024ULL * 1024ULL};
};

[[nodiscard]] Result<ScriptProgram> parse_script(std::string_view text, ScriptLimits limits = {});

/// Outcome of applying one command. Reported per line so a partial failure is
/// visible rather than fatal.
struct ScriptStepResult {
  std::size_t line{0};
  std::string verb{};
  StatusCode code{StatusCode::Ok};
  std::string detail{};
  std::string output{};
};

struct ScriptRunResult {
  std::vector<ScriptStepResult> steps{};
  std::vector<ScriptDiagnostic> diagnostics{};
  std::size_t applied{0};
  std::size_t failed{0};
  bool cancelled{false};

  /// True only when every command was applied and the scenario parsed without
  /// errors: a line the parser refused is a failure, not a silent omission.
  [[nodiscard]] bool ok() const noexcept {
    if (failed != 0 || cancelled) {
      return false;
    }
    for (const ScriptDiagnostic& diagnostic : diagnostics) {
      if (diagnostic.severity == "error") {
        return false;
      }
    }
    return true;
  }
  [[nodiscard]] std::size_t diagnostic_errors() const noexcept;
  [[nodiscard]] std::string render() const;
};

/// Applies a parsed program to an engine. p token allows a long script to be
/// cancelled between commands.
[[nodiscard]] ScriptRunResult apply_script(ObservatoryEngine& engine, const ScriptProgram& program,
                                           std::stop_token token = {});

/// Helpers shared with the CLI for parsing values out of command fields.
[[nodiscard]] Result<std::uint64_t> parse_u64(std::string_view text);
[[nodiscard]] Result<std::int64_t> parse_i64(std::string_view text);
[[nodiscard]] Result<bool> parse_bool(std::string_view text);
[[nodiscard]] Result<Timestamp> parse_time_or_offset(std::string_view text, Timestamp relative_to);
[[nodiscard]] Result<Endpoint> parse_endpoint(std::string_view text);
[[nodiscard]] Result<std::vector<Hop>> parse_hops(std::string_view text);

}  // namespace loss_observatory
